# Generated by Django 5.0.2 on 2024-07-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descrpt', models.TextField()),
                ('price', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
