# Generated by Django 5.0.2 on 2024-07-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='benz',
            field=models.CharField(default='Petrol', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carlist',
            name='seats',
            field=models.CharField(default='5', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carlist',
            name='price',
            field=models.CharField(default='$31/day', max_length=31),
        ),
    ]
