# Generated by Django 5.0.2 on 2024-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carlist_benz_carlist_seats_alter_carlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
