# Generated by Django 5.0.2 on 2024-07-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='slug',
        ),
    ]
