# Generated by Django 5.0.2 on 2024-07-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_carlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
