# Generated by Django 5.0.2 on 2024-07-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
